# Generated by Django 5.1 on 2024-08-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('encrypted', models.BooleanField(default=False)),
                ('encryption_key', models.CharField(blank=True, max_length=44)),
            ],
        ),
    ]
